# Remap escape key to the tick/tilda key from Ctrl+b
unbind C-b
set -g prefix `
bind-key ` last-window
bind-key e send-prefix
# set -g default-command $SHELL

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Changing navigation keys to vi mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Status bar
set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
set -g status-left ''
set -g status-right 'Anakin #[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M '
set -g status-right-length 50
set -g status-left-length 20
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

# Set history limit 50000 lines
set-option -g history-limit 50000

# tmux windows start at 1
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# set the scrolling behavior of the mouse
set -g mouse on

# Install Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize Tmux Package Manager
run '~/.tmux/plugins/tpm/tpm'
